version: "3.7"

services:
  mariadb:
    image: mariadb:10.4.8
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mariadb:/var/lib/mysql
    networks: 
      - default

volumes:
  mariadb:

