# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CACHED_DEPENDENCY_PATHS: ${{ github.workspace }}/node_modules
  BUILD_CACHE_KEY: ${{ github.sha }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  init:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Check out current commit (${{ github.sha }})
        uses: actions/checkout@v2
      
      - name: Set up Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - name: dependency cache key
        id: lockfile_hash
        run: echo "::set-output name=hash::${{ hashFiles('yarn.lock') }}"

      - name: Check dependency cache
        uses: actions/cache@v2
        id: cache-dependencies
        with:
          path: ${{ env.CACHED_DEPENDENCY_PATHS }}
          key: ${{ steps.lockfile_hash.outputs.hash }}
      
      - name: Install dependencies
        if: steps.cache_dependenceis.outputs.cache-hit != 'true'
        run: yarn 
    outputs:
      dependency_cache_key: ${{ steps.lockfile_hash.outputs.hash }}


  # build:
  #   name: Build
  #   needs: init
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Use Nodejs
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '16'
  #     - name: Check dependency cache
  #       uses: actions/cache@v2
  #       with: 
  #         path: ${{ env.CACHED_DEPENDENCY_PATHS }}
  #         key: ${{ needs.init.outputs.dependency_cache_key }}
  #     - name: Check build cache
  #       uses: actions/cache@v2
  #       id: cache_built_package
  #       with:
  #         path:
  #         key:


      

      # 중간에 실패한 경우 슬랙으로 알려줍니다.
      # GitHub 저장소나 조직의 Secrets 항목에 슬랙 Webhook URL을 등록해야 합니다.
      # - name: Notify failure
      #   uses: 8398a7/action-slack@v3
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      #   with:
      #     status: ${{ job.status }}
      #     username: github-actions
      #     channel: '#github'
      #   if: failure()

